### ISSUE TITLE
Fail to install with mamba

### ISSUE THREAD

**Issue by hadim** [psi4/psi4#2621]
Reproduce with the below env.yml file:

```yaml
channels:
  - conda-forge
  - psi4

dependencies:
  - python =3.9
  - datamol  
  - numpy
  - scikit-learn
  - pytorch >=1.10.2
  - tqdm
  - jupyterlab
  - openmm
  - psi4 >=1.6
```

then `mamba env create -n tmp_psi4 -f env.yml` and the error is

```
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
psi4/linux-64                                                 No change
psi4/noarch                                                   No change


Looking for: ['python=3.10', 'datamol', 'numpy', 'scikit-learn', "pytorch[version='>=1.10.2']", 'tqdm', 'jupyterlab', 'openmm', "psi4[version='>=1.6']"]


Encountered problems while solving:
  - nothing provides intel-openmp needed by psi4-1.6+77475b5-py39hceaf722_0
```

I tried multiple combination of python and psi4 versions without success.

Note that the above has been only tested on a linux machine.
